name: Update Memecoins Weekly

on:
  schedule:
    - cron: '0 10 * * 1'  # Tous les lundis à 10h UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install node-fetch

      - name: Générer le fichier memecoins.json
        run: node scripts/update-memecoins.js

      - name: Commit et push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add memecoins.json
          git commit -m "🤖 Mise à jour automatique des memecoins" || echo "Aucun changement"
          git push
