name: FIST-DETECTOR
on:
  schedule:
    - cron: '0 10 * * 1' # Chaque lundi à 10h UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scripts/weekly_memecoin.py

      - name: Commit & Push
        run: |
          git config --global user.name "FIST-BOT"
          git config --global user.email "fistbot@users.noreply.github.com"
          git add data/memecoin.json
          git commit -m "Weekly update 🚀"
          git push

